apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po
spec:
  containers:
    -
      args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:80
      command:
        - /usr/bin/php
      env:
        -
          name: author
          value: Rojas
      image: fernandorojascuesta/phpinfo:latest
      name: phpinfo-container
      ports:
        -
          containerPort: 8080
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests:
          cpu: 100m
          memory: 100M
      volumeMounts:
        -
          mountPath: /app/
          name: public
          readOnly: true
      workingDir: /app/
  initContainers:
    -
      args:
        - git clone https://github.com/frojascu/phpinfo ;
        - cd phpinfo ;
        - git checkout 2021-09-santander ;
        - cp -r src/index.php /public/ ;
      command:
        - /bin/sh
        - -c
      env:
        -
          name: author
          value: Rojas
      image: alpine/git:1.0.30@sha256:0595334722a2d486ed7c1a10a9138180f052343d5569942ecceb88d6e7fd1c0f
      name: phpinfo-git
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests:
          cpu: 100m
          memory: 100M
      volumeMounts:
        -
          mountPath: /private/
          name: private
          readOnly: false
        -
          mountPath: /public/
          name: public
          readOnly: false
      workingDir: /private/
  volumes:
    -
      emptyDir:
        medium: Memory
        sizeLimit: 1M
      name: private
    -
      emptyDir:
        medium: Memory
        sizeLimit: 1M
      name: public
status: {}
