apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpinfo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1M
    requests:
      storage: 1M
  storageClassName: gp2
  volumeMode: Filesystem
status: {}
