apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-cm-1
  namespace: fernando-phpinfo
spec:
  replicas: 3
  selector:
    name: phpinfo-po-cm
    version: "1"
  template:
    metadata:
      labels:
        name: phpinfo-po-cm
        version: "1"
    spec:
      containers:
        -
          args:
            - -f
            - index.php
            - -S
            - 0.0.0.0:8080
          command:
            - /usr/bin/php
          env:
            -
              name: author
              value: NEW
          image: fernandorojascuesta/phpinfo:latest
          livenessProve:
            tcpSocket:
              port: 8080
          name: phpinfo-container
          ports:
            -
              containerPort: 8080
              protocol: TCP
          redinessProbe:
            httpGet:
              path: /index.php
              port: 8080
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
          volumeMounts:
            -
              mountPath: /app/
              name: public
              readOnly: true
          workingDir: /app/
      volumes:
        -  
          ## wget https://raw.githubusercontent.com/jose-escallada/phpinfo/2021-09-santander/src/index.php
          ## oc create configmap index.php --from-file=index.php
          ## kubectl create configmap index.php --from-file=index.php
          configMap:
            defaultMode: 0400
            items:
              -
                key: index.php
                mode: 0400
                path: index.php
            name: index.php
          name: public    
