services:
  phpinfo-svc:
    image: secobau/phpinfo:1.6
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          memory: 32Mi
        reservations:
          memory: 32Mi
    healthcheck:
      interval: 10s
      start_period: 30s
      test: php -r "print file_get_contents('http://localhost:8080/');"
      timeout: 1s
    ports:
    - "8080:8080"
version: "3.8"
