apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phpinfo-helm
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - env: '1'
      - env: '2'
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      labels:
        applicationset: phpinfo-helm
      name: phpinfo-helm-{{ env }}
    spec:
      destination:
        namespace: phpinfo-helm-{{ env }}
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        helm:
          valueFiles:
          - phpinfo-helm-{{ env }}/values.yaml
        path: main/helm/
        repoURL: https://github.com/sebastian-colomar/phpinfo.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
