apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phpinfo-helm-provider-aws-helm-odds
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: provider-aws-helm-odds
  template:
    metadata:
      name: phpinfo-helm-{{name}}
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values.yaml
        path: main/apps/helm
        repoURL: https://github.com/sebastian-colomar/phpinfo
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: phpinfo-helm-{{name}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
